[package]
name = "eruption-gui"
version = "0.0.1"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "A GUI for the Eruption Linux user-mode driver"
repository = "https://github.com/X3n0m0rph59/eruption-roccat-vulcan.git"
homepage = "https://github.com/X3n0m0rph59/eruption-roccat-vulcan"
license = "GPLv3+"
readme = "README.md"

[dependencies]
# async-std = { version = "1.6.2", features = ["attributes", "tokio02"] }
# async-macros = "2.0.0"
clap = "3.0.0-beta.2"
clap_derive = "3.0.0-beta.1"
colored = "2.0"
log = "0.4.11"
pretty_env_logger = "0.4.0"
libc = "0.2.78"
nix = "0.18.0"
rayon = "1.4.1"
walkdir = "2.3.1"
parking_lot = { version = "0.11.0", features = ["deadlock_detection"] }
serde = { version = "1.0.116", features = ["derive"] }
serde_json = { version = "1.0.58" }
# tokio = { version = "0.2.22", features = ["full", "parking_lot"] }
tracing = "0.1.21"
tracing-futures = "0.2.4"
tracing-subscriber = "0.2.12"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
toml = "0.5.6"
itertools = "0.9.0"
lazy_static = "1.4.0"
thiserror = "1.0.20"
eyre = "0.6.1"
color-eyre = "0.5.5"
paste = "1.0"
dbus = "0.9.0"
dbus-tokio = "0.5.2"

[dependencies.gtk]
version = "0.9.2"
features = ["v3_22"]

[dependencies.sourceview]
version = "0.9.0"
features = ["v3_22"]

[dependencies.gdk]
version = "0.13.2"
features = ["v3_22"]

[dependencies.gdk-pixbuf]
version = "0.9.0"

[dependencies.glib]
version = "0.10.2"

[dependencies.cairo-rs]
version = "0.9.1"

[dependencies.gio]
version = "0.9.1"
features = ["v2_44"]

[dev-dependencies]
tokio = { version = "0.2", features = ["test-util"] }
