[package]
name = "eruption-netfx"
version = "0.0.1"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "A Network FX protocol client for the Eruption Linux user-mode driver"
repository = "https://github.com/X3n0m0rph59/eruption-roccat-vulcan.git"
homepage = "https://github.com/X3n0m0rph59/eruption-roccat-vulcan"
license = "GPLv3+"
readme = "README.md"

[dependencies]
# async-std = { version = "1.6.2", features = ["attributes", "tokio02"] }
# async-macros = "2.0.0"
clap = "3.0.0-beta.2"
clap_derive = "3.0.0-beta.1"
colored = "2.0"
log = "0.4.11"
pretty_env_logger = "0.4.0"
libc = "0.2.79"
nix = "0.19.0"
rayon = "1.5.0"
walkdir = "2.3.1"
parking_lot = { version = "0.11.0", features = ["deadlock_detection"] }
serde = { version = "1.0.117", features = ["derive"] }
serde_json = { version = "1.0.59" }
tokio = { version = "0.2", features = ["full", "parking_lot"] }
tracing = "0.1.21"
tracing-futures = "0.2.4"
tracing-subscriber = "0.2.13"
thiserror = "1.0.21"
eyre = "0.6.1"
color-eyre = "0.5.6"
num-traits = "0.2.12"
image = "0.23.10"
x11 = { version = "2.18.2", features = ["xlib", "xrandr"] }

[dev-dependencies]
tokio = { version = "0.2", features = ["test-util"] }
