on: [push, pull_request]
name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
     - name: Setup Dependencies
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install -y -qq libusb-1.0-0-dev libhidapi-dev libevdev-dev libudev-dev	libdbus-1-dev libpulse-dev luajit libluajit-5.1-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
